// <auto-generated />
namespace TripRadar.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DeletedLocationFKinTripaddedAddressStringinLoc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DeletedLocationFKinTripaddedAddressStringinLoc));
        
        string IMigrationMetadata.Id
        {
            get { return "201902132115227_Deleted LocationFK in Trip, added Address String in Loc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
