// <auto-generated />
namespace TripRadar.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class PropAddedinTripModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PropAddedinTripModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201902131445412_Prop Added in Trip Model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
